export enum DealsQueryKeys {
  GET_DEALS_LIST = 'GET_DEALS_LIST',
  GET_SUBMITTED_DEALS_LIST = 'GET_SUBMITTED_DEALS_LIST',
  GET_REPORTED_ISSUES_LIST = 'GET_REPORTED_ISSUES_LIST',
  GET_DEAL_REQUESTS_LIST = 'GET_DEAL_REQUESTS_LIST',
  GET_DEALS_COUNTS = 'GET_DEALS_COUNTS',
  GET_DEALS_WHITELIST = 'GET_DEALS_WHITELIST',
}
