export const DemoDaysQueryKeys = {
  GET_DEMO_DAYS_LIST: 'GET_DEMO_DAYS_LIST',
  GET_DEMO_DAY_DETAILS: 'GET_DEMO_DAY_DETAILS',
  GET_DEMO_DAY_PARTICIPANTS: 'GET_DEMO_DAY_PARTICIPANTS',
  GET_DEMO_DAY_SUBSCRIBERS: 'GET_DEMO_DAY_SUBSCRIBERS',
  GET_DASHBOARD_WHITELIST: 'GET_DASHBOARD_WHITELIST',
} as const;
