process.env.AIRTABLE_API_KEY = 'MOCK_AIRTABLE_API_KEY';
process.env.AIRTABLE_BASE_ID = 'MOCK_AIRTABLE_BASE_ID';
process.env.AIRTABLE_TEAMS_TABLE_ID = 'MOCK_AIRTABLE_TEAMS_TABLE_ID';
process.env.AIRTABLE_MEMBERS_TABLE_ID = 'MOCK_AIRTABLE_MEMBERS_TABLE_ID';
