-- Add DELETE lifecycle values to the AI Apps enums.
ALTER TYPE "AiAppStatus" ADD VALUE IF NOT EXISTS 'DELETING';
ALTER TYPE "AiAppStatus" ADD VALUE IF NOT EXISTS 'DELETED';

ALTER TYPE "AiAppEventType" ADD VALUE IF NOT EXISTS 'DELETE_STARTED';
ALTER TYPE "AiAppEventType" ADD VALUE IF NOT EXISTS 'DELETE_SUCCEEDED';
ALTER TYPE "AiAppEventType" ADD VALUE IF NOT EXISTS 'DELETE_FAILED';
