export enum MembersQueryKeys {
  GET_MEMBERS_LIST = 'GET_MEMBERS_LIST',
  GET_MEMBERS_ACCESS_LEVEL_COUNTS = 'GET_MEMBERS_ACCESS_LEVEL_COUNTS',
  GET_SKILLS_OPTIONS = 'GET_SKILLS_OPTIONS',
  GET_MEMBER = 'GET_MEMBER',
  GET_SIGN_UP_SOURCES = 'GET_SIGN_UP_SOURCES',
}
