name: 'Sync branches on push to main'

on:
  push:
    branches:
      - main

jobs:
  main-push-sync:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Rebase the `main` branch onto the `staging` branch
        run: |
          git checkout staging
          git rebase origin/main
          git push

      - name: Rebase the `staging` branch onto the `develop` branch
        run: |
          git checkout develop
          git rebase origin/staging
          git push
