name: 'Sync branches on push to main'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main-push-sync:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0
          token: ${{ secrets.PLN_BOT_TOKEN }}

      - name: Set Git config
        run: |
          git config --local user.email "pln-dev@pixelmatters.com"
          git config --local user.name "PLN-Helper"

      - name: Rebase the `main` branch onto the `staging` branch
        run: |
          git rebase origin/main
          git push

      - name: Rebase the `staging` branch onto the `develop` branch
        run: |
          git checkout develop
          git rebase origin/staging
          git push
