name: 'Staging Deployment'

on:
  workflow_dispatch:
  schedule:
    # run every day at 8 AM
    - cron: '0 8 * * *'

jobs:
  check-new-commits-develop:
    runs-on: ubuntu-20.04
    outputs:
      NEW_COMMITS: ${{ steps.check-new-commits.outputs.NEW_COMMITS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if there are new commits on `develop` branch
        id: check-new-commits
        run: echo "NEW_COMMITS=$(git rev-list --count origin/staging..origin/develop)" >> $GITHUB_OUTPUT

  rebase:
    runs-on: ubuntu-20.04
    needs: check-new-commits-develop
    if: needs.check-new-commits-develop.outputs.NEW_COMMITS > 0
    steps:
      - name: Checkout code from the `staging` branch
        uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0
          token: ${{ secrets.PLN_BOT_TOKEN }}

      - name: Set Git config
        run: |
          git config --local user.email "bot@plnetwork.io"
          git config --local user.name "PLN-Helper"

      - name: Rebase the `staging` branch onto the `develop` branch
        run: |
          git rebase origin/develop
          git push --force
